/* Generated by updaterev.sh, do not edit */
#ifdef SDL_VENDOR_INFO
#define SDL_REVISION "SDL-2.30.11-g13745df (" SDL_VENDOR_INFO ")"
#else
#define SDL_REVISION "SDL-2.30.11-g13745df"
#endif
#define SDL_REVISION_NUMBER 0
